name: 'Lambda Action'
description: 'Validade , build and deploy AWS Lambdas'
inputs:
  lambda_deployment_secret:
    required: true
  lambda_deployment_key:
    required: true
  serverless_deployment_bucket:
    required: true
  team:  # id of input
    description: 'The name of the team. egg: backend, frontend, growth'
    required: true
  eslint_project_list:
    description: 'A list of subproject separated by comma. If it is just one project on root dir, use just one `.`'
    required: true
  ignore_lint_errors:
    description: 'In case of the project has many errors, turning not viable fix all now, change this value to not break the build'
    required: false
    default: false
  project_name:
    description: 'The name used in the spreadsheet'
    required: true

outputs:
  errors:
    description: 'The number of errors in this project'
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run npm install for the list of projects
        env:
          PROJECT_LIST: "${{ inputs.project_list }}"
        run: ${{ github.action_path }}/install.sh
        shell: bash

      - name: 'Run eslint and send data to collector'
        uses: edgardleal/code-quality-to-spreadsheet-action@main
        env:
          DEBUG: 'eslint-collector*'
          CONTINUE_ON_ERROR: ${{ inputs.ignore_lint_errors }}
        with:
          spreadsheet_id: ${{ inputs.spreadsheet_id }}
          google_service_account_email: ${{ inputs.google_service_account_email }}
          google_private_key: ${{ inputs.google_private_key }}
          eslint_project_list: ${{ inputs.eslint_project_list }}
          project_name: ${{ inputs.project_name }}

      - name: Run tests
        env:
          PROJECT_LIST: "${{ inputs.project_list }}"
        run: ${{ github.action_path }}/tests.sh
        shell: bash

      - name: Deployment
        env:
          SERVERLESS_DEPLOYMENT_BUCKET: ${{ inputs.serverless_deployment_bucket }} 
          AWS_ACCESS_KEY_ID: ${{ inputs.lambda_deployment_key }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.lambda_deployment_secret }}
          BRANCH: ${{ github.ref }}
        run: ${{ github.action_path }}/deploy.sh
        shell: bash

          # - name: Slack Notification
          #   if: contains(github.ref, 'master') || contains(github.ref, 'main') || contains(github.ref, 'develop')
          #   uses: rtCamp/action-slack-notify@v2
          #   env:
          #     SLACK_CHANNEL: eng-releases
          #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          #     SLACK_ICON: https://img.icons8.com/small/452/github.png
          #     SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          #     SLACK_TITLE: ${{ inputs.project_name }}
          #     SLACK_USERNAME: GithubAction
          #     SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
      
